<?php

$name = $alerts->location->name;
$country = $alerts->location->country;
$alertweather = $alerts->alerts->alert;

?>

<?php
if (isset($alerts)) { ?>
 <?php foreach($alertweather as $val){ ?>

<form action="alerts" method="post">
<div class="d-flex my-4 border p-3">
  <div class="card-body">
    <p class="card-text"><b>City: </b>&nbsp;<?php echo $name."<br>"; ?></p>
    <p class="card-text"><b>Country: </b>&nbsp;<?php echo $country."<br>"; ?></p>
    <p class="card-text"><b>Headline: </b>&nbsp;<?php echo $val->headline."<br>"; ?></p>
    <p class="card-text"><b>Message: </b>&nbsp;<?php echo $val->msgtype."<br>"; ?></p>
    <p class="card-text"><b>Areas: </b>&nbsp;<?php echo $val->areas."<br>"; ?></p>
    <p class="card-text"><b>Event: </b>&nbsp;<?php echo $val->event."<br>"; ?></p>
    <p class="card-text"><b>Note: </b>&nbsp;<?php echo $val->note."<br>"; ?></p>
    <p class="card-text"><b>Effective: </b>&nbsp;<?php echo $val->effective."<br>"; ?></p>
    <p class="card-text"><b>Expires: </b>&nbsp;<?php echo $val->expires."<br>"; ?></p>
    <p class="card-text"><b>Description: </b>&nbsp;<?php echo $val->desc."<br>"; ?></p>


</div>
</div>
</form>
<?php } ?>
<?php
}
?>